### ISSUE TITLE
[Bug]: Hide option gets overridden on state change like maximizing a window

### ISSUE THREAD

**Issue by nlambert** [luisbocanegra/plasma-panel-colorizer#98] opened 2024-10-19 02:08 UTC
- [x] I have searched if this issue hasn't been reported yet.

**Describe the bug**
The title says it all, but to be clear I am referring to the checkbox option labelled "hide widget (visible in panel edit mode)"

When that option is checked the icon is indeed hidden but only until the state is changed like when maximizing a window.

**To Reproduce**
1. Check the option
2. Be sure to have a preset that is autoloading under any of the four conditions (normal, floating, touching or window maximized)
3. Trigger that state
4. See the icon reappear

**Expected behavior**
Should not reappear

**Project version**
Says 0.5.2 in the about section but I installed 1.0.0-1 version of plasma6-applets-panel-colorizer

**Desktop (please complete the following information):**
 - Operating System: Arch Linux
 - KDE Plasma Version: 6.2.1
 - KDE Frameworks Version: 6.7.0
 - Qt Version: [e.g. 6.8.0]
 - Graphics Platform: Wayland

**Comment by luisbocanegra** [comment] 2024-10-19 02:18
Can't reproduce here

> Says 0.5.2 in the about section but I installed 1.0.0-1 version of plasma6-applets-panel-colorizer

Have you restarted after updating the widget? I've seen the same thing after updating without rebooting or restarting plasmashell, after doing so it shows the correct version, my guess is the widget is in a weird state now having the state of the old versions clashing with the new one

**Comment by luisbocanegra** [comment] 2024-10-19 02:19
Which is expected because things work differently after the rewrite and also the way the configuration is stored

**Comment by luisbocanegra** [comment] 2024-11-10 01:59
Closing as I have been unable to reproduce this, if you still do please let me know.

**Closed by luisbocanegra** 2024-11-10 01:59 UTC
Labels: bug

**Comment by nlambert** [comment] 2024-11-10 02:02
Oh sorry yes you are right to close, it was user error, and the clue was in the project version saying 2 things... it was installed in 2 places without me realizing it. Thanks for following up.
