### ISSUE TITLE
[Bug] Light/Dark theme transitions broken by Panel Colorizer

### ISSUE THREAD

**Issue by marcosilva85** [luisbocanegra/plasma-panel-colorizer#41] opened 2024-04-20 13:45 UTC
Hi, I love the different ways Panel Colorizer enables to transform our setups.
In my case, I use it simply to add more panel transparency and making a highlight on the Window Title widget.

Though it works, there is a small bug that is an annoyance when switching within light/dark themes, or by doing so via the kde Night-light feature that does this transition automatically on certain times.

Panel Colorizer messes up with the transition switch from dark->light or light->dark theme , and as a result the colors of the icons are kept in an incorrect state. This is a bug because I don't have any overrides on "Text and Icons", which is actually disabled.
See screenshots attached - you can see because Panel Colorizer is active, sadly the icons and most of other widgets were not allowed to change out of the white color to black, when actually under a Light theme they should turn black:
![1 dark](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/10670060/29f3ff83-9593-4c8b-86ad-d481c5148601)
![2 dark-to-light-problems](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/10670060/64128e9d-a7a8-42ac-b9a7-b88101ac1584)
See this last screenshot showing how a proper Breeze Light theme:
![3 how-light-should-look-like](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/10670060/0bd54c19-9afc-4bf4-8074-a50280e66c66)

Interestingly - if I change any setting at all in Panel Colorizer and apply, suddenly the light/dark theme properly applies. Even if I toggle a setting and apply, like "contrast correction" from a section that I don't even have enabled (Text and Icons), still the theme suddenly properly applies, which is even more interesting.

I can send my profile if required, but should be easy to reproduce.
Given that, perhaps there's an easy fix for this?

**Comment by luisbocanegra** [comment] 2024-04-20 19:01
Can reproduce, will try to have it fixed as soon as I can. In the meantime you can enable **Text and icons** with these settings as a workaround:

Source: System
Color: Text
Color set: Background
Contrast correction: unchecked

**Comment by luisbocanegra** [comment] 2024-04-20 19:34
> Interestingly - if I change any setting at all in Panel Colorizer and apply, suddenly the light/dark theme properly applies. Even if I toggle a setting and apply, like "contrast correction" from a section that I don't even have enabled (Text and Icons), still the theme suddenly properly applies, which is even more interesting.

Property applying from disabled sections should not change panel appearance, that is a bug.

Panel reloading will still happen when changing settings from disabled sections, because I reload the theme if any setting changes instead of having to check each of options (89 currently!), not a bug.

The unintended reload is what is causing the colors to update, but if they are disabled they shouldn't change at all but follow the system instead, this is the bug causing the broken dark/light transition (probably just need to do something similar to what I did for https://github.com/luisbocanegra/plasma-wallpaper-effects/commit/aa3de2f6ebb9539a54708dea78e26a1b50a6d401)

**Comment by luisbocanegra** [comment] 2024-05-18 04:01
Commit https://github.com/luisbocanegra/plasma-panel-colorizer/commit/c073e3e9c7b52b35053a9ad738956876ee0f93b5 should fix this.

To test do one of these:

- Clone and run `./install.sh` (assuming the build dependencies are installed)
- Or clone and run `kpackagetool6 -t Plasma/Applet -u package/` inside the project
- Easiest, download the file below and run `kpackagetool6 -t Plasma/Applet -u plasmoid-panel-colorizer-v0.5.2.zip`

[plasmoid-panel-colorizer-v0.5.2.zip](https://github.com/luisbocanegra/plasma-panel-colorizer/files/15359738/plasmoid-panel-colorizer-v0.5.2.zip)

**Comment by luisbocanegra** [comment] 2024-05-18 04:45
Just noticed some errors, hold on the testing

**Comment by luisbocanegra** [comment] 2024-05-18 04:50
I have updated the file, should be good now

**Comment by luisbocanegra** [comment] 2024-05-27 10:56
This should be fixed in [v0.5.2](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/tag/v0.5.2)[v0.5.2](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/tag/v0.5.2).

**Closed by luisbocanegra** 2024-05-27 10:56 UTC
Labels: bug, needs testing
